ARG BASE_IMAGE=cimg/base:current
FROM $BASE_IMAGE

ARG BASE_IMAGE
ARG OTP_VERSION
ARG TARGETARCH
ARG SETUP
ARG OPENSSL_VERSION

USER root

RUN --mount=type=bind,src=tools,dst=/tools \
    /tools/prepare.sh compile

RUN --mount=type=bind,src=tools,dst=/tools \
    /tools/openssl_setup.sh compile

RUN --mount=type=bind,src=tools,dst=/tools \
    /tools/erlang_setup.sh compile
